Repository ansible-community/molecule-docker, pull requests merged in 2021-05, with the labels that each got.

#49 Pass stop_signal and kill_signal to docker_container in create.yml
  molecule_docker/playbooks/create.yml
Labels: enhancement

#51 change docker image build path
  molecule_docker/driver.py
  molecule_docker/playbooks/cleanup.yml
  molecule_docker/playbooks/create.yml
Labels: enhancement

#55 Fix condition when path is missing
  molecule_docker/playbooks/create.yml
Labels: bug

#54 Address deprecation warning
  molecule_docker/playbooks/destroy.yml
Labels: bug

#56 fix: specify docker modules namespace
  molecule_docker/driver.py
  molecule_docker/playbooks/create.yml
  molecule_docker/playbooks/destroy.yml
  molecule_docker/playbooks/validate-dockerfile.yml
Labels: bug

#58 Rely on community.docker collection
  .ansible.cfg
  .github/workflows/tox.yml
  README.rst
  ansible.cfg
  molecule_docker/driver.py
  molecule_docker/playbooks/create.yml
  molecule_docker/playbooks/destroy.yml
  molecule_docker/test/test_func.py
  setup.cfg
  tox.ini
Labels: major

#59 Add extra static test
  .github/workflows/tox.yml
  molecule/default/converge.yml
  molecule/default/molecule.yml
  molecule/default/verify.yml
  molecule_docker/test/test_func.py
Labels: test

#60 Pass stop_signal and kill_signal to docker_container in create.yml (#49)
  molecule_docker/playbooks/create.yml
Labels: bug

#65 Update default branch references
  .github/workflows/release-drafter.yml
  .github/workflows/tox.yml
Labels: skip-changelog
