Repository ansible-community/molecule-docker, pull requests merged in 2021-07, with the labels that each got.

#72 change freenode to libera
  README.rst
Labels: documentation

#73 Enable ansible-lint
  .pre-commit-config.yaml
  molecule_docker/playbooks/create.yml
  molecule_docker/playbooks/validate-dockerfile.yml
Labels: bug

#74 Bump linters
  .pre-commit-config.yaml
Labels: skip-changelog

#75 Remove flake8-black
  .pre-commit-config.yaml
Labels: skip-changelog

#76 Assure reviewers are added automatically to PRs
  .github/CODEOWNERS
Labels: skip-changelog

#77 Expose required collection
  molecule_docker/driver.py
Labels: feature

#71 remove state statement
  molecule_docker/playbooks/destroy.yml
Labels: bug
