Repository ansible-community/molecule-docker, pull requests merged in 2022-07, with the labels that each got.

#153 Fix container building test
  molecule/default/molecule.yml
  src/molecule_docker/driver.py
  src/molecule_docker/playbooks/validate-dockerfile.yml
Labels: skip-changelog

#154 Update CODEOWNERS
  .github/CODEOWNERS
Labels: skip-changelog

#156 Require ansible-core 2.12 or newer
  .github/workflows/tox.yml
  tox.ini
Labels: major

#157 Require molecule 4.0 or newer
  setup.cfg
Labels: major

#148 Add docker_host option in README
  README.rst
Labels: bug

#160 Add support for py310 and py311
  .github/workflows/tox.yml
  setup.cfg
Labels: bug
