Repository ansible-community/molecule-docker, pull requests merged in 2022-08, with the labels that each got.

#167 Remove py38-devel in tox as ansible@devel dropped support for py38
  .github/workflows/tox.yml
Labels: enhancement

#169 Sync docker context
  .github/workflows/tox.yml
  requirements.yml
  src/molecule_docker/driver.py
  src/molecule_docker/playbooks/create.yml
  src/molecule_docker/test/scenarios/with-context/molecule/default/Dockerfile.j2
  src/molecule_docker/test/scenarios/with-context/molecule/default/FOO
  src/molecule_docker/test/scenarios/with-context/molecule/default/converge.yml
  src/molecule_docker/test/scenarios/with-context/molecule/default/molecule.yml
  src/molecule_docker/test/test_func.py
Labels: bug

#171 bump community.docker dependency to a released version
  requirements.yml
  src/molecule_docker/driver.py
Labels: skip-changelog
